import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import Header from "@/components/base/header";
import Footer from "@/components/base/footer";

const noto = Noto_Sans_JP({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${noto.className} min-h-[100vh] relative pb-10 antialiased bg-gray-100`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
